services:
    caddy:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: caddy
        env_file:
            - ./caddy.env
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - /var/run/docker.sock:/var/run/docker.sock
            - caddy_data:/data
            - caddy_config:/config
            - ./ssl:/ssl
        extra_hosts:
            - host.docker.internal:host-gateway

volumes:
    caddy_data: {}
    caddy_config:
